apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-producao-app
data:
  SPRING_DATASOURCE_URL: jdbc:mariadb://rds-fiap-tech-challenge.czedzxpic1u6.us-east-1.rds.amazonaws.com:3306/producaodb
  SPRING_JPA_SHOW: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  URI_API_PEDIDO_ATUALIZAR_STATUS: http://svc-pedido-app/pedido-app/api/pedidos
  AWS_SQS_IN_PRODUCAO_NAME: lanchonete-producao-queue.fifo
  AWS_SQS_OUT_PEDIDO_STATUS_URI: https://sqs.us-east-1.amazonaws.com/786426553713/lanchonete-pedido-status-queue.fifo
  RECEBER_PEDIDO_PRODUCAO_ENABLED: "true"
 
