apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-producao-app
data:
  SPRING_DATASOURCE_URL: jdbc:mariadb://rds-fiap-tech-challenge.cbl891k9286k.us-east-1.rds.amazonaws.com:3306/producaodb
  SPRING_JPA_SHOW: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  AWS_SQS_URI: https://sqs.us-east-1.amazonaws.com/797459365217/teste.fifo
  URI_API_PEDIDO_ATUALIZAR_STATUS: http://svc-pedido-app/pedido-app/api/pedidos
  AWS_SQS_NAME: teste.fifo
  AWS_ACCESS_KEY_ID: ASIA3TLCIHVQ6X5VZOGB
  AWS_SECRET_ACCESS_KEY: DYImPEUzIDYJN3fRIXumIjo7YWtLOU4Hz2650OIg
  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjELb//////////wEaCXVzLXdlc3QtMiJHMEUCIQDZqbVG279yAnd8GE9D6qclasuoJyY8EuZitjLwd2yVpAIgLCo1KF8H8z+QO+pHphQl6OuXD0HtgTngrmFSLNvdC+EqrQIIHxABGgw3OTc0NTkzNjUyMTciDGhHJjM9AZjAtFo9JSqKAgkvZES2oe/LwkhngkZw2R457mG6GmUiJFz527moNW79m0xM9fEXa3uoOBSAL4UmZUbjxbX4Ng6sMLxHw+Hh1Ix51K53zrU7fjtE5d0zBctc5GBVPWrcuLGFnkxI6qpYiqiBJMuqFEU/jZGvfDJCFqNabjaZTo8G6xK/QAi7iOBjIakKzYNHf4xWpFjuK6V2YcVzAheGgC+M9dtSTu3oKV5+2ozaP0g0zId4dBrI3Eb20sCoJL3dZgiRCyjfK3udsYvqEtoclT+gBzsVG6HvDjdrTUVtZ3Rvxq32ftGIv8GgrBhlTo1SVkOTZXUvAXkuobJU7mfACtys66ZfEBrZm6TVxIiyuH+TDcYHMNL99LEGOp0BhcCyR5X/x9YgQdNORcxBfsYssUnEZsxMEff6QWSTvMSp+gv/KxhbaZMYQ5k8I8q4WkPInRUVHQ/E2lZSTtZW2Xw9dIf93NGgrcYcQKSvSb7pGPouKNlcpnoPRnQ+lbBERpXhraCj5M1cDzHChXPjMF3R4Y0LDklMwFvWRNjr2f8nDZoc3oQslUm3sjIh44gx2ZFOcITNSiegX2qAuQ==
