apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-aws
data:
  AWS_ACCESS_KEY_ID: ASIA3TLCIHVQ45GUALOX
  AWS_SECRET_ACCESS_KEY: KDyHJEGbzQIOt9cX16pNF1hkq+8/p49RajQTAw3C
  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjELr//////////wEaCXVzLXdlc3QtMiJHMEUCIF9D4HAbO/ODk6rIR/cEZwwD+VkvrMrZzpAHxTEeU3NyAiEAiWZwg2KSfUNn3GC1qGRFwE8Yu85yGqNJdzFC0rQo5b0qrQIIIxABGgw3OTc0NTkzNjUyMTciDAIVxry7o8bPceKieiqKAqfIT+imcQ+K53uUmf8bcp98d+0vZE1OHTWmdXA3iC8WP/eLJwO4fHGHqoT734A+hLFV9ZxGDGZJMYRIwMDJufD5L412tDFedZuvtrdD/UyFnGyid+oxN1Aj8Mq4GpKSD/D9sUgmmOztl71FZUlarunnVhCpZMPN3FNfGboplbXsxUaGuQRJ7XM77ur8wuVWKv6GY0LuQ6LOLgCKCdoelUPnJo1mhqjHZIFcW1cMyWz4BV8ipRgXltfvG9II0EsmSWuhPBEPgXlH3obkTGh2jJJWpwIHPIw+d8g0gyLSWVakyae/l9I5nuPstNhET7Aksvu1fqHGV8omLFSubnFtxqxtKrl3T/rfYVdQMPjw9bEGOp0BSj5iBGhLsM5xHLkHpjlnp/8tjFs2ZdNu0Sg1clLDR+GtPEejhF3kAehiIRqqZOuoNLegeufUEI4dfl/ou6rAW2dSZbI/0qLgz+GIs0DBZtG12rFucjeac9cG6XDrBnLAy+javmnKO/iS9b7yqMLwbeCU5K+6T3xyOMc6uKs8N/NYBdZ8o8PLpVD2icdWfHm+e7ASfagK3rGcj7yXuw==
